/**
 * Shell completion generation -- static scripts and dynamic runtime completions.
 * Matches clap_complete's feature set: bash, zsh, fish, powershell.
 *
 * Two modes:
 * 1. Static: generateCompletions() returns a shell script string to source
 * 2. Dynamic: completeEnv() checks env vars, outputs completions, returns true if handled
 */

import type { ArgDef, CommandDef, Shell, ValueHint } from './types.js';

// ---- Internal: Command Tree Traversal ----

interface FlagInfo {
  key: string;
  short?: string;
  long: string;
  description: string;
  takesValue: boolean;
  possibleValues: readonly string[];
  valueHint?: ValueHint;
  hidden: boolean;
}

interface SubcommandInfo {
  name: string;
  description: string;
  aliases: readonly string[];
  hidden: boolean;
}

interface CompletionNode {
  name: string;
  flags: FlagInfo[];
  subcommands: SubcommandInfo[];
  childNodes: Map<string, CompletionNode>;
}

/** Extract completion-relevant data from a CommandDef tree. */
function buildCompletionTree(command: CommandDef, name?: string): CompletionNode {
  const flags: FlagInfo[] = [];
  const argsDef = command.args ?? {};

  for (const [key, def] of Object.entries(argsDef)) {
    if (def.type === 'positional') {
      continue;
    }
    const longName = def.long ?? key;
    flags.push({
      key,
      short: def.short,
      long: longName,
      description: def.description ?? '',
      takesValue: def.type !== 'boolean' && def.action !== 'count',
      possibleValues: Array.isArray(def.valueParser) ? def.valueParser : [],
      valueHint: def.valueHint,
      hidden: def.hidden ?? false,
    });
  }

  // Always include --help and --version
  flags.push({ key: 'help', short: 'h', long: 'help', description: 'Print help', takesValue: false, possibleValues: [], hidden: false });
  if (command.meta.version) {
    flags.push({ key: 'version', short: 'V', long: 'version', description: 'Print version', takesValue: false, possibleValues: [], hidden: false });
  }

  const subcommands: SubcommandInfo[] = [];
  const childNodes = new Map<string, CompletionNode>();

  if (command.subCommands) {
    for (const [subName, subDef] of Object.entries(command.subCommands)) {
      subcommands.push({
        name: subName,
        description: subDef.meta.description ?? '',
        aliases: subDef.meta.aliases ?? [],
        hidden: subDef.meta.hidden ?? false,
      });
      childNodes.set(subName, buildCompletionTree(subDef, subName));
    }
  }

  return {
    name: name ?? command.meta.name,
    flags,
    subcommands,
    childNodes,
  };
}

// ---- Helpers ----

/** Escape single quotes for shell strings. */
function esc(s: string): string {
  return s.replaceAll("'", "'\\''");
}

/** Escape double quotes for shell strings. */
function escDq(s: string): string {
  return s.replaceAll('"', '\\"').replaceAll('$', '\\$').replaceAll('`', '\\`');
}

/** Sanitize a name for use as a shell function/variable name. */
function sanitize(s: string): string {
  return s.replaceAll(/[^a-zA-Z0-9_]/g, '_');
}

// ---- Bash Generator ----

function generateBash(root: CompletionNode, binaryName: string): string {
  const funcName = `_${sanitize(binaryName)}`;
  const lines: string[] = [];

  lines.push(`# bash completion for ${binaryName}`);
  lines.push(`# Generated by clap-ts`);
  lines.push('');

  // Generate completion function for each command level
  generateBashFunction(root, funcName, binaryName, lines);

  lines.push('');
  lines.push(`complete -o default -o bashdefault -F ${funcName} ${binaryName}`);
  lines.push('');

  return lines.join('\n');
}

function generateBashFunction(
  node: CompletionNode,
  funcName: string,
  fullCommand: string,
  lines: string[],
): void {
  lines.push(`${funcName}() {`);
  lines.push('    local cur prev words cword');
  lines.push('    _init_completion || return');
  lines.push('');

  // Build flag list
  const visibleFlags = node.flags.filter((f) => !f.hidden);
  const flagWords: string[] = [];
  for (const f of visibleFlags) {
    flagWords.push(`--${f.long}`);
    if (f.short) {
      flagWords.push(`-${f.short}`);
    }
  }

  // Build subcommand list
  const visibleSubs = node.subcommands.filter((s) => !s.hidden);
  const subWords = visibleSubs.map((s) => s.name);

  // Handle value completion for flags that take values
  const valueFlagCases: string[] = [];
  for (const f of visibleFlags) {
    if (!f.takesValue) continue;
    const flagNames = [`--${f.long}`];
    if (f.short) flagNames.push(`-${f.short}`);
    const pattern = flagNames.join('|');

    if (f.possibleValues.length > 0) {
      valueFlagCases.push(`        ${pattern})`);
      valueFlagCases.push(`            COMPREPLY=( $(compgen -W '${f.possibleValues.join(' ')}' -- "$cur") )`);
      valueFlagCases.push('            return ;;');
    } else if (f.valueHint) {
      const compgen = bashValueHintCompgen(f.valueHint);
      if (compgen) {
        valueFlagCases.push(`        ${pattern})`);
        valueFlagCases.push(`            ${compgen}`);
        valueFlagCases.push('            return ;;');
      }
    }
  }

  if (valueFlagCases.length > 0) {
    lines.push('    case "$prev" in');
    lines.push(...valueFlagCases);
    lines.push('    esac');
    lines.push('');
  }

  // Handle subcommand dispatch
  if (visibleSubs.length > 0) {
    lines.push('    # Check for subcommand');
    lines.push('    local subcmd=""');
    lines.push('    for ((i=1; i < cword; i++)); do');
    lines.push('        case "${words[i]}" in');
    for (const sub of visibleSubs) {
      const allNames = [sub.name, ...sub.aliases];
      lines.push(`            ${allNames.join('|')})`);
      lines.push(`                subcmd="${sub.name}"; break ;;`);
    }
    lines.push('        esac');
    lines.push('    done');
    lines.push('');

    // Dispatch to child function
    lines.push('    case "$subcmd" in');
    for (const sub of visibleSubs) {
      const childFunc = `${funcName}_${sanitize(sub.name)}`;
      lines.push(`        ${sub.name})`);
      lines.push(`            ${childFunc}; return ;;`);
    }
    lines.push('    esac');
    lines.push('');
  }

  // Default: complete with flags and subcommands
  const allWords = [...flagWords, ...subWords].join(' ');
  lines.push(`    COMPREPLY=( $(compgen -W '${allWords}' -- "$cur") )`);
  lines.push('}');
  lines.push('');

  // Recurse for child commands
  for (const sub of visibleSubs) {
    const childNode = node.childNodes.get(sub.name);
    if (childNode) {
      const childFunc = `${funcName}_${sanitize(sub.name)}`;
      generateBashFunction(childNode, childFunc, `${fullCommand} ${sub.name}`, lines);
    }
  }
}

function bashValueHintCompgen(hint: ValueHint): string | undefined {
  switch (hint) {
    case 'filePath': return 'COMPREPLY=( $(compgen -f -- "$cur") )';
    case 'dirPath': return 'COMPREPLY=( $(compgen -d -- "$cur") )';
    case 'anyPath': return 'COMPREPLY=( $(compgen -f -- "$cur") )';
    case 'executablePath': return 'COMPREPLY=( $(compgen -c -- "$cur") )';
    case 'commandName': return 'COMPREPLY=( $(compgen -c -- "$cur") )';
    case 'hostname': return 'COMPREPLY=( $(compgen -A hostname -- "$cur") )';
    case 'username': return 'COMPREPLY=( $(compgen -u -- "$cur") )';
    case 'url': return undefined;
    case 'emailAddress': return undefined;
  }
}

// ---- Zsh Generator ----

function generateZsh(root: CompletionNode, binaryName: string): string {
  const funcName = `_${sanitize(binaryName)}`;
  const lines: string[] = [];

  lines.push(`#compdef ${binaryName}`);
  lines.push('');
  lines.push(`# zsh completion for ${binaryName}`);
  lines.push('# Generated by clap-ts');
  lines.push('');

  generateZshFunction(root, funcName, lines);

  lines.push('');
  lines.push(`if [ "$funcstack[1]" = "${funcName}" ]; then`);
  lines.push(`    ${funcName} "$@"`);
  lines.push('else');
  lines.push(`    compdef ${funcName} ${binaryName}`);
  lines.push('fi');
  lines.push('');

  return lines.join('\n');
}

function generateZshFunction(
  node: CompletionNode,
  funcName: string,
  lines: string[],
): void {
  lines.push(`${funcName}() {`);
  lines.push('    local -a args');
  lines.push('');

  const visibleFlags = node.flags.filter((f) => !f.hidden);
  const visibleSubs = node.subcommands.filter((s) => !s.hidden);

  // Build _arguments specs for flags
  const argSpecs: string[] = [];
  for (const f of visibleFlags) {
    const desc = escDq(f.description);
    if (f.takesValue) {
      const valueSpec = zshValueSpec(f);
      if (f.short) {
        argSpecs.push(`'(-${f.short} --${f.long})-${f.short}[${desc}]${valueSpec}'`);
        argSpecs.push(`'(-${f.short} --${f.long})--${f.long}[${desc}]${valueSpec}'`);
      } else {
        argSpecs.push(`'--${f.long}[${desc}]${valueSpec}'`);
      }
    } else {
      if (f.short) {
        argSpecs.push(`'(-${f.short} --${f.long})-${f.short}[${desc}]'`);
        argSpecs.push(`'(-${f.short} --${f.long})--${f.long}[${desc}]'`);
      } else {
        argSpecs.push(`'--${f.long}[${desc}]'`);
      }
    }
  }

  if (visibleSubs.length > 0) {
    argSpecs.push("'1: :->command'");
    argSpecs.push("'*::arg:->args'");
  }

  if (argSpecs.length > 0) {
    lines.push('    _arguments -C \\');
    for (let i = 0; i < argSpecs.length; i++) {
      const sep = i < argSpecs.length - 1 ? ' \\' : '';
      lines.push(`        ${argSpecs[i]}${sep}`);
    }
    lines.push('');
  }

  if (visibleSubs.length > 0) {
    lines.push('    case "$state" in');
    lines.push('        command)');
    const subDescs = visibleSubs.map((s) => `'${s.name}:${escDq(s.description)}'`);
    lines.push(`            _values 'command' ${subDescs.join(' ')}`);
    lines.push('            ;;');
    lines.push('        args)');
    lines.push('            case "$words[1]" in');
    for (const sub of visibleSubs) {
      const childFunc = `${funcName}_${sanitize(sub.name)}`;
      const allNames = [sub.name, ...sub.aliases];
      lines.push(`                ${allNames.join('|')})`);
      lines.push(`                    ${childFunc} ;;`);
    }
    lines.push('            esac');
    lines.push('            ;;');
    lines.push('    esac');
  }

  lines.push('}');
  lines.push('');

  // Recurse for child commands
  for (const sub of visibleSubs) {
    const childNode = node.childNodes.get(sub.name);
    if (childNode) {
      const childFunc = `${funcName}_${sanitize(sub.name)}`;
      generateZshFunction(childNode, childFunc, lines);
    }
  }
}

function zshValueSpec(f: FlagInfo): string {
  if (f.possibleValues.length > 0) {
    const vals = f.possibleValues.join(' ');
    return `:${f.key}:(${vals})`;
  }
  if (f.valueHint) {
    return zshValueHintSpec(f.valueHint, f.key);
  }
  return `:${f.key}:`;
}

function zshValueHintSpec(hint: ValueHint, key: string): string {
  switch (hint) {
    case 'filePath': return `:${key}:_files`;
    case 'dirPath': return `:${key}:_directories`;
    case 'anyPath': return `:${key}:_files`;
    case 'executablePath': return `:${key}:_command_names`;
    case 'commandName': return `:${key}:_command_names`;
    case 'hostname': return `:${key}:_hosts`;
    case 'username': return `:${key}:_users`;
    case 'url': return `:${key}:_urls`;
    case 'emailAddress': return `:${key}:`;
  }
}

// ---- Fish Generator ----

function generateFish(root: CompletionNode, binaryName: string): string {
  const lines: string[] = [];

  lines.push(`# fish completion for ${binaryName}`);
  lines.push('# Generated by clap-ts');
  lines.push('');

  generateFishCommands(root, binaryName, [], lines);

  return lines.join('\n');
}

function generateFishCommands(
  node: CompletionNode,
  binaryName: string,
  parentSubcommands: string[],
  lines: string[],
): void {
  const visibleFlags = node.flags.filter((f) => !f.hidden);
  const visibleSubs = node.subcommands.filter((s) => !s.hidden);

  // Build condition: only show these completions when we're at this command level
  let condition: string;
  if (parentSubcommands.length === 0) {
    if (visibleSubs.length > 0) {
      // Root level with subcommands: show only when no subcommand has been seen
      const allSubNames = collectAllSubcommandNames(node);
      condition = `not __fish_seen_subcommand_from ${allSubNames.join(' ')}`;
    } else {
      condition = '';
    }
  } else {
    const lastSub = parentSubcommands[parentSubcommands.length - 1]!;
    condition = `__fish_seen_subcommand_from ${lastSub}`;
  }

  const condFlag = condition ? `-n '${condition}'` : '';

  // Register flags
  for (const f of visibleFlags) {
    const parts = [`complete -c ${binaryName}`];
    if (condFlag) parts.push(condFlag);
    if (f.short) parts.push(`-s ${f.short}`);
    parts.push(`-l ${f.long}`);
    if (f.description) parts.push(`-d '${esc(f.description)}'`);
    if (f.takesValue) {
      parts.push('-r'); // requires argument
      if (f.possibleValues.length > 0) {
        parts.push(`-a '${f.possibleValues.join(' ')}'`);
      } else if (f.valueHint) {
        const fishHint = fishValueHint(f.valueHint);
        if (fishHint) parts.push(fishHint);
      }
    }
    lines.push(parts.join(' '));
  }

  // Register subcommands
  for (const sub of visibleSubs) {
    const parts = [`complete -c ${binaryName}`];
    if (condFlag) parts.push(condFlag);
    parts.push(`-a '${sub.name}'`);
    if (sub.description) parts.push(`-d '${esc(sub.description)}'`);
    lines.push(parts.join(' '));

    // Also register aliases
    for (const alias of sub.aliases) {
      const aliasParts = [`complete -c ${binaryName}`];
      if (condFlag) aliasParts.push(condFlag);
      aliasParts.push(`-a '${alias}'`);
      if (sub.description) aliasParts.push(`-d '${esc(sub.description)}'`);
      lines.push(aliasParts.join(' '));
    }
  }

  lines.push('');

  // Recurse for child commands
  for (const sub of visibleSubs) {
    const childNode = node.childNodes.get(sub.name);
    if (childNode) {
      generateFishCommands(childNode, binaryName, [...parentSubcommands, sub.name], lines);
    }
  }
}

function collectAllSubcommandNames(node: CompletionNode): string[] {
  const names: string[] = [];
  for (const sub of node.subcommands) {
    if (!sub.hidden) {
      names.push(sub.name);
      names.push(...sub.aliases);
    }
  }
  return names;
}

function fishValueHint(hint: ValueHint): string | undefined {
  switch (hint) {
    case 'filePath': return '-F';
    case 'dirPath': return "-xa '(__fish_complete_directories)'";
    case 'anyPath': return '-F';
    case 'executablePath': return "-a '(__fish_complete_command)'";
    case 'commandName': return "-a '(__fish_complete_command)'";
    case 'hostname': return "-a '(__fish_print_hostnames)'";
    case 'username': return "-a '(__fish_complete_users)'";
    case 'url': return undefined;
    case 'emailAddress': return undefined;
  }
}

// ---- PowerShell Generator ----

function generatePowerShell(root: CompletionNode, binaryName: string): string {
  const lines: string[] = [];

  lines.push(`# PowerShell completion for ${binaryName}`);
  lines.push('# Generated by clap-ts');
  lines.push('');
  lines.push(`Register-ArgumentCompleter -CommandName '${binaryName}' -ScriptBlock {`);
  lines.push('    param($wordToComplete, $commandAst, $cursorPosition)');
  lines.push('');
  lines.push('    $tokens = $commandAst.CommandElements | ForEach-Object { $_.ToString() }');
  lines.push('    $tokens = $tokens[1..($tokens.Length - 1)]  # Remove command name');
  lines.push('');

  generatePowerShellNode(root, '    ', '$tokens', 0, lines);

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

function generatePowerShellNode(
  node: CompletionNode,
  indent: string,
  tokensVar: string,
  depth: number,
  lines: string[],
): void {
  const visibleFlags = node.flags.filter((f) => !f.hidden);
  const visibleSubs = node.subcommands.filter((s) => !s.hidden);

  // Check if we need to dispatch to a subcommand
  if (visibleSubs.length > 0) {
    lines.push(`${indent}# Check for subcommand at position ${depth}`);
    lines.push(`${indent}if (${tokensVar}.Length -gt ${depth}) {`);
    lines.push(`${indent}    switch (${tokensVar}[${depth}]) {`);
    for (const sub of visibleSubs) {
      const allNames = [sub.name, ...sub.aliases].map((n) => `'${n}'`).join(', ');
      lines.push(`${indent}        {$_ -in ${allNames}} {`);

      const childNode = node.childNodes.get(sub.name);
      if (childNode) {
        generatePowerShellNode(childNode, indent + '            ', tokensVar, depth + 1, lines);
      }

      lines.push(`${indent}            return`);
      lines.push(`${indent}        }`);
    }
    lines.push(`${indent}    }`);
    lines.push(`${indent}}`);
    lines.push('');
  }

  // Complete flags and subcommands at this level
  const completions: string[] = [];
  for (const f of visibleFlags) {
    const desc = escDq(f.description);
    completions.push(`${indent}[System.Management.Automation.CompletionResult]::new('--${f.long}', '--${f.long}', 'ParameterName', '${escDq(f.description)}')`);
    if (f.short) {
      completions.push(`${indent}[System.Management.Automation.CompletionResult]::new('-${f.short}', '-${f.short}', 'ParameterName', '${escDq(f.description)}')`);
    }
  }
  for (const sub of visibleSubs) {
    completions.push(`${indent}[System.Management.Automation.CompletionResult]::new('${sub.name}', '${sub.name}', 'Command', '${escDq(sub.description)}')`);
  }

  for (const c of completions) {
    lines.push(c);
  }
}

// ---- Public API: Static Generation ----

/**
 * Generate a shell completion script for the given command and shell.
 *
 * Usage:
 * ```ts
 * const script = generateCompletions(rootCommand, 'bash', 'my-cli');
 * fs.writeFileSync('completions.bash', script);
 * ```
 *
 * Users source the generated script in their shell config:
 * - bash: `source completions.bash` or copy to `~/.local/share/bash-completion/completions/`
 * - zsh: copy to a directory in `$fpath` (e.g., `~/.zsh/completions/`)
 * - fish: copy to `~/.config/fish/completions/`
 * - powershell: add to `$PROFILE`
 */
export function generateCompletions(
  command: CommandDef,
  shell: Shell,
  binaryName?: string,
): string {
  const name = binaryName ?? command.meta.name;
  const root = buildCompletionTree(command, name);

  switch (shell) {
    case 'bash': return generateBash(root, name);
    case 'zsh': return generateZsh(root, name);
    case 'fish': return generateFish(root, name);
    case 'powershell': return generatePowerShell(root, name);
  }
}

// ---- Public API: Dynamic Completion ----

/**
 * Check for the `CLAP_COMPLETE` environment variable and output dynamic completions.
 * Returns `true` if completions were handled (caller should exit), `false` otherwise.
 *
 * Usage in runMain or manually:
 * ```ts
 * if (completeEnv(rootCommand)) {
 *   process.exit(0);
 * }
 * ```
 *
 * Shell setup (add to .bashrc):
 * ```bash
 * _myapp() {
 *   local IFS=$'\n'
 *   COMPREPLY=($(CLAP_COMPLETE=bash COMP_LINE="$COMP_LINE" COMP_POINT="$COMP_POINT" myapp))
 * }
 * complete -o default -F _myapp myapp
 * ```
 */
export function completeEnv(command: CommandDef): boolean {
  const shell = process.env['CLAP_COMPLETE'];
  if (!shell) {
    return false;
  }

  const compLine = process.env['COMP_LINE'] ?? '';
  const compPoint = Number.parseInt(process.env['COMP_POINT'] ?? String(compLine.length), 10);

  // Parse the line up to cursor position into tokens
  const lineUpToCursor = compLine.slice(0, compPoint);
  const tokens = tokenize(lineUpToCursor);

  // Remove the binary name (first token)
  tokens.shift();

  const endsWithSpace = lineUpToCursor.endsWith(' ');

  // The word being completed: last token if not followed by space, empty otherwise
  const partial = endsWithSpace ? '' : (tokens[tokens.length - 1] ?? '');

  // Tokens to walk for subcommand resolution: all completed tokens (exclude partial being typed)
  const completedTokens = endsWithSpace ? tokens : tokens.slice(0, -1);

  // Walk the command tree using only fully-typed tokens
  let current = command;
  let consumed = 0;
  while (consumed < completedTokens.length && current.subCommands) {
    const token = completedTokens[consumed]!;
    if (token.startsWith('-')) break;

    // Direct match
    const sub = current.subCommands[token];
    if (sub) {
      current = sub;
      consumed++;
      continue;
    }

    // Alias match
    let found = false;
    for (const [name, def] of Object.entries(current.subCommands)) {
      if (def.meta.aliases?.includes(token)) {
        current = def;
        consumed++;
        found = true;
        break;
      }
    }
    if (!found) break;
  }

  // Determine the previous completed token (for flag value completion)
  const prevToken = completedTokens.length > 0
    ? completedTokens[completedTokens.length - 1]
    : undefined;

  const completions = getCompletionsForContext(current, partial, prevToken, endsWithSpace);

  // Output completions to stdout
  for (const c of completions) {
    process.stdout.write(`${c}\n`);
  }

  return true;
}

/** Tokenize a command line string, respecting quotes. */
function tokenize(line: string): string[] {
  const tokens: string[] = [];
  let current = '';
  let inSingle = false;
  let inDouble = false;

  for (let i = 0; i < line.length; i++) {
    const c = line[i]!;
    if (c === "'" && !inDouble) {
      inSingle = !inSingle;
    } else if (c === '"' && !inSingle) {
      inDouble = !inDouble;
    } else if (c === ' ' && !inSingle && !inDouble) {
      if (current.length > 0) {
        tokens.push(current);
        current = '';
      }
    } else {
      current += c;
    }
  }
  if (current.length > 0) {
    tokens.push(current);
  }

  return tokens;
}

/** Get completions for the current command context and partial input. */
function getCompletionsForContext(
  command: CommandDef,
  partial: string,
  prevToken: string | undefined,
  endsWithSpace: boolean,
): string[] {
  const results: string[] = [];
  const argsDef = command.args ?? {};

  // If previous token is a flag that takes a value, complete its values
  if (prevToken && endsWithSpace) {
    const flagDef = findFlagDef(argsDef, prevToken);
    if (flagDef && flagDef.type !== 'boolean' && flagDef.action !== 'count') {
      if (Array.isArray(flagDef.valueParser) && flagDef.valueParser.length > 0) {
        return flagDef.valueParser.filter((v) => v.startsWith(partial));
      }
      // For value hints, return empty (shell handles file/dir completion)
      return [];
    }
  }

  // Complete flags
  for (const [key, def] of Object.entries(argsDef)) {
    if (def.type === 'positional' || def.hidden) continue;
    const longName = `--${def.long ?? key}`;
    if (longName.startsWith(partial)) {
      results.push(longName);
    }
    if (def.short && `-${def.short}`.startsWith(partial)) {
      results.push(`-${def.short}`);
    }
  }

  // Complete subcommands
  if (command.subCommands) {
    for (const [name, def] of Object.entries(command.subCommands)) {
      if (def.meta.hidden) continue;
      if (name.startsWith(partial)) {
        results.push(name);
      }
      if (def.meta.aliases) {
        for (const alias of def.meta.aliases) {
          if (alias.startsWith(partial)) {
            results.push(alias);
          }
        }
      }
    }
  }

  // Always include --help
  if ('--help'.startsWith(partial)) results.push('--help');
  if ('-h'.startsWith(partial)) results.push('-h');

  return results;
}

/** Find the ArgDef for a given flag token (--long or -s). */
function findFlagDef(argsDef: Record<string, ArgDef>, token: string): ArgDef | undefined {
  if (token.startsWith('--')) {
    const name = token.slice(2);
    for (const [key, def] of Object.entries(argsDef)) {
      if ((def.long ?? key) === name) return def;
    }
  } else if (token.startsWith('-') && token.length === 2) {
    const short = token[1]!;
    for (const def of Object.values(argsDef)) {
      if (def.short === short) return def;
    }
  }
  return undefined;
}
